#  Tags are assigned to the corresponding resources being created.
#    "application" represents team name, e.g. 'probate', 'divorce', use 'core' for platform infrastructure.
#    "businessArea" represents the business area this application belongs to, one of CFT / Crime / Cross-Cutting.
#  Further docs: https://tools.hmcts.net/confluence/display/DCO/Tagging+v0.4

sds-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

cft-platform:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "CFT"

soc:
  team: "soc"
  namespace: ""
  slack:
    contact_channel: "#sec-ops"
    build_notices_channel: ""
  tags:
    application: "security"
    businessArea: "Cross-Cutting"

ethos:
  team: "ethos"
  namespace: ""
  slack:
    contact_channel: "#ethos-repl-service"
    build_notices_channel: ""
  tags:
    application: "ethos"
    businessArea: "Cross-Cutting"

heritage:
  team: "heritage"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "heritage"
    businessArea: "Cross-Cutting"

mi:
  team: "mi"
  namespace: ""
  slack:
    contact_channel: "#mi-data-platform"
    build_notices_channel: ""
  tags:
    application: "management-information"
    businessArea: "Cross-Cutting"

pet:
  team: "pet"
  namespace: ""
  slack:
    contact_channel: "#pet-devops"
    build_notices_channel: ""
  tags:
    application: "pet"
    businessArea: "Cross-Cutting"

robotics:
  team: "robotics"
  namespace: ""
  slack:
    contact_channel: "#robotics"
    build_notices_channel: ""
  tags:
    application: "robotics"
    businessArea: "Cross-Cutting"

mgmt:
  team: "mgmt"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: ""
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

hub:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

sds-jenkins:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"

mailrelay:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
hmi:
  team: "hmi"
  namespace: ""
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: ""
  tags:
    application: "hearing-management-interface"
    businessArea: "Cross-Cutting"
toffee:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
netbox:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: "core"
    businessArea: "Cross-Cutting"
juror-digital:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: ""
    build_notices_channel: ""
  tags:
    application: "Juror Digital"
    businessArea: "Cross-Cutting"
ctsc:
  team: "CTSC"
  namespace: "ctsc"
  slack:
    contact_channel: "#ctsc-master-builds"
    build_notices_channel: "#ctsc-master-builds"
  tags:
    application: 'courts-tribunals-service-centre'
    businessArea: "Cross-Cutting"
vh:
  team: "Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'Video Hearings'
    businessArea: "Cross-Cutting"
wowza:
  team: "Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'Video Hearings'
    businessArea: "Cross-Cutting"
pip:
  team: "Publishing and Information"
  namespace: "pip"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'Publishing and Information'
    businessArea: "Cross-Cutting"
cvp:
  team: "Cloud Video Platform"
  namespace: "cvp"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: 'Cloud Video Platform'
    businessArea: "Cross-Cutting"
shared-image-gallery:
  team: "platform operations"
  namespace: ""
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: 'core'
    businessArea: "Cross-Cutting"